table Calendar
	lineageTag: b103e3f9-77be-4525-a6c5-388fc625b273

	column date
		dataType: dateTime
		formatString: d/m/yyyy
		lineageTag: 75effd28-eaff-4278-b974-9b953caf0d78
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 5bce1bfd-2633-41d2-84b9-ded54429c88a
			defaultHierarchy: LocalDateTable_4dde7c04-65d4-4d63-bdce-6c03be865e7a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 99a66f9f-9e85-4c83-b5cf-81eea0668041
		summarizeBy: none
		sourceColumn: Start of Week

		variation Variation
			isDefault
			relationship: ee4fe129-e504-4969-b5de-aad138963597
			defaultHierarchy: LocalDateTable_6a1624bb-eb54-4587-9c99-152505c61a07.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Name'
		dataType: string
		lineageTag: 8d3a09a8-3bd3-4153-a1ca-17d5b450c3f9
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cdcb642a-d910-4fad-81e8-afe3d0207dc0
		summarizeBy: none
		sourceColumn: Start of Month

		variation Variation
			isDefault
			relationship: 1a08c0be-1e51-45e4-bbda-8edb90f7d461
			defaultHierarchy: LocalDateTable_f5932301-3275-4261-8349-37afc5ae35a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Name'
		dataType: string
		lineageTag: 63d1bf63-e84d-477c-823d-83a1a09fbb15
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 7a4856b6-424a-4500-998d-4860ed8e8a14
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ac3e02e3-13f6-48e9-ad46-91d9026c02a0
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Name of Day'
		dataType: string
		lineageTag: 4c95ad09-9f35-46d5-a4d6-bc4c7c97d07c
		summarizeBy: none
		sourceColumn: Name of Day

		annotation SummarizationSetBy = Automatic

	column Weekend = ```
			IF('Calendar'[Name of Day] = "Saturday" ||'Calendar'[Name of Day] = "Sunday","Y", "N")
			
			
			```
		lineageTag: 96093d8e-053d-4e89-8381-0117baa73311
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'End of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e09be07-cad2-4191-a5ff-075d5afcab23
		summarizeBy: none
		sourceColumn: End of Month

		variation Variation
			isDefault
			relationship: d82eb98d-0578-4c60-b1d0-4ac5938354cf
			defaultHierarchy: LocalDateTable_c713703e-220f-4910-9a53-ffa138e4836a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Calendar = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NatalijaSuharevska\OneDrive - Direct Medics Ltd\Desktop\Power BI_Dev_Maven Market\MavenMarket_Calendar.csv"),[Delimiter=",", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}}),
				    #"Inserted Start of Week" = Table.AddColumn(#"Changed Type1", "Start of Week", each Date.StartOfWeek([date]), type date),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Start of Week", "Day Name", each Date.DayOfWeekName([Start of Week]), type text),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Day Name", "Start of Month", each Date.StartOfMonth([Start of Week]), type date),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Start of Month", "Month Name", each Date.MonthName([Start of Week]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Start of Week]), Int64.Type),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Quarter", "Year", each Date.Year([Start of Week]), Int64.Type),
				    #"Inserted Day Name1" = Table.AddColumn(#"Inserted Year", "Day Name.1", each Date.DayOfWeekName([date]), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Day Name1",{{"Day Name.1", "Name of Day"}}),
				    #"Inserted End of Month" = Table.AddColumn(#"Renamed Columns", "End of Month", each Date.EndOfMonth([date]), type date)
				in
				    #"Inserted End of Month"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

