table Calendar
	lineageTag: b103e3f9-77be-4525-a6c5-388fc625b273
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: dd/mm/yy
		lineageTag: 75effd28-eaff-4278-b974-9b953caf0d78
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 99a66f9f-9e85-4c83-b5cf-81eea0668041
		summarizeBy: none
		sourceColumn: Start of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Name'
		dataType: string
		lineageTag: 8d3a09a8-3bd3-4153-a1ca-17d5b450c3f9
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cdcb642a-d910-4fad-81e8-afe3d0207dc0
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 7a4856b6-424a-4500-998d-4860ed8e8a14
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Name of Day'
		dataType: string
		lineageTag: 4c95ad09-9f35-46d5-a4d6-bc4c7c97d07c
		summarizeBy: none
		sourceColumn: Name of Day

		annotation SummarizationSetBy = Automatic

	column Weekend = ```
			IF('Calendar'[Name of Day] = "Saturday" ||'Calendar'[Name of Day] = "Sunday","Y", "N")
			
			
			```
		lineageTag: 96093d8e-053d-4e89-8381-0117baa73311
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'End of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e09be07-cad2-4191-a5ff-075d5afcab23
		summarizeBy: none
		sourceColumn: End of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Year'
		dataType: string
		lineageTag: 94da2ef2-72db-4bdb-873c-9dd0ab91357a
		summarizeBy: none
		sourceColumn: Month Year
		sortByColumn: 'Start of Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Month = FORMAT('Calendar'[date], "MMMM")
		lineageTag: 53cff7fe-bbc6-4c55-bb66-f4135abfd515
		summarizeBy: none
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Number' = MONTH('Calendar'[date])
		formatString: 0
		lineageTag: 2dd90084-28c9-4b79-85ce-8484ef90feaa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Year = YEAR('Calendar'[date])
		formatString: 0
		lineageTag: 89c572d2-6b82-4859-9924-70041542b7e9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsData = ```
			VAR LastDataDate =
			    CALCULATE(MAX('Transaction Data'[Transaction_date]), ALL('Transaction Data'))
			        RETURN 
			        IF('Calendar'[date] <= LastDataDate,1,0)
			```
		formatString: 0
		lineageTag: 74b3109b-a87a-4e8a-8e15-a195d0c05076
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'date Hierarchy'
		lineageTag: 8e210d45-c9ed-4af5-ab6c-d83d271bc942

		level date
			lineageTag: 35614853-01e8-4a3d-bf75-67d21ba92fb7
			column: date

		level 'Month Year'
			lineageTag: eb915d29-b41a-4a5d-994f-9fb45f5b24a4
			column: 'Month Year'

	partition Calendar = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\AI-PowerBI-Lab_NS\Projects\Maven Market\MavenMarket_Calendar.csv"),[Delimiter=",", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Promoted Headers", {{"date", type date}}, "en-GB"),
				    #"Inserted Start of Week" = Table.AddColumn(#"Changed Type with Locale", "Start of Week", each Date.StartOfWeek([date]), type date),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Start of Week", "Day Name", each Date.DayOfWeekName([Start of Week]), type text),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Day Name", "Start of Month", each Date.StartOfMonth([Start of Week]), type date),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Start of Month", "Month Name", each Date.MonthName([Start of Week]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Start of Week]), Int64.Type),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Quarter", "Year", each Date.Year([Start of Week]), Int64.Type),
				    #"Inserted Day Name1" = Table.AddColumn(#"Inserted Year", "Day Name.1", each Date.DayOfWeekName([date]), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Day Name1",{{"Day Name.1", "Name of Day"}}),
				    #"Inserted End of Month" = Table.AddColumn(#"Renamed Columns", "End of Month", each Date.EndOfMonth([date]), type date),
				    #"Split Column by Position" = Table.SplitColumn(#"Inserted End of Month", "Month Name", Splitter.SplitTextByPositions({0, 3}, false), {"Month Name.1", "Month Name.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Position",{{"Month Name.1", type text}, {"Month Name.2", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Month Name.2"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Month Name.1", "Month Name"}}),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Renamed Columns1", {{"Year", type text}}, "en-GB"),{"Month Name", "Year"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Merged"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Merged Columns",{{"Merged", "Month Year"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

