table Regions
	lineageTag: 5f09e9ff-a042-4d58-a86d-dc83ce85632b

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: a11fce15-183f-45f2-b1e4-de84eaffe20a
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column sales_district
		dataType: string
		lineageTag: f53af426-b4a7-41f6-b211-50ab5ccaaac0
		summarizeBy: none
		sourceColumn: sales_district

		annotation SummarizationSetBy = Automatic

	column sales_region
		dataType: string
		lineageTag: 03ec130f-a32b-4bec-b11f-c7cd94f62dcf
		summarizeBy: none
		sourceColumn: sales_region

		annotation SummarizationSetBy = Automatic

	partition Regions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NatalijaSuharevska\OneDrive - Direct Medics Ltd\Desktop\Power BI_Dev_Maven Market\MavenMarket_Regions.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"region_id", Int64.Type}, {"sales_district", type text}, {"sales_region", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

